### ISSUE TITLE
Deprecate this repo in pro to use only pre-commit-vauxoo

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/pre-commit-vauxoo-hooks#4]
Move the hooks of this repository to use directly in the .pre-commit-config.yaml from:
 - https://github.com/Vauxoo/pre-commit-vauxoo

But as `local` ones

I mean, define in the setup.py a binary for:
 - https://github.com/Vauxoo/pre-commit-vauxoo-hooks/blob/main/src/check_deactivate_jinja.py

Copy this file

And add to .pre-commit-config.yaml the following

```yaml
- repo: local
  - id: vx-check-deactivate
    name: Check deactivate.jinja syntax
    description: Check if the file deactivate.jinja is correctly formatted
    entry: vx-check-deactivate
    args: []
    language: python
    types: [jinja]
    files: ^deactivate\.jinja$
```

Or something similar

I just realize that pre-commit-vauxoo-hooks is not working in an isolated way for vauxoo but OCA

Advantages:
 - The unittest are very strong in pre-commit-vauxoo
 - We avoid releasing 2 packages for each new change in the hooks
